### PR TITLE
Surface Plotting

### LINKED ISSUE #42: Improve the style of labels in optimization plots
@robfairh pointed out that the plotting in ``optimizers.py`` could be improved by making the labels more readable.

Current behavior: 
If optimizing over ``trainlen`` (the training length) the "visualize" option will create a plot titled "MSE as a function of trainlen."
Other examples:
rho --> rho
n_reservoir --> n_reservoir

Desired behavior: 
The plot labels should be more readable. So rather than having "... function of trainlen" it should read "function of Training Length."
Other examples:
rho --> spectral radius, $\rho$ (where \rho is the actual greek letter, rendered by LaTeX with matplotlib). 
n_reservoir --> reservoir size

Guidance:
Rather than creating a bunch of if-statements to figure out which variables are being tested, it is probably best to use a dictionary of key-value. The "key" should be the parameter being optimized and the "value" should be the string. 

e.g. 

```python
labels = {'rho' : r'Spectral Radius $\rho$', 'n_reservoir' : 'Reservoir Size', [...add your code here...]}

# Do stuff, then plot it

plt.xlabel(labels['rho'])
plt.ylabel(labels['n_reservoir'])
```

### LINKED ISSUE #49: Update the plotting functions to allow for 3D surfaces
3D surfaces can be better for visualizing error minima than 2D heat maps.

This issue can be closed when the ``grid_optimizer`` function has been updated to change
``visualize = True`` to the options ``visualize = (None, 2D, 3D)``

### PR DESCRIPTION
**Pull request by samgdotson**
Adds the ability to plot surfaces rather than heat maps for grid optimization.
Includes example in a cosine notebook.

Closes #42 and Closes #49

### CODE REVIEW

**Comment by samgdotson** [comment]
I'm not sure why the CircleCI build isn't showing up here, but it was triggered and did successfully build. 
[link to circleci](https://app.circleci.com/pipelines/github/arfc/cairo/47/workflows/41bd22c7-2145-463f-a30c-88fa132f341f/jobs/51).

**Comment by robfairh** [comment]
Any idea what is going on here?

image

And also here

image

**Comment by samgdotson** [comment]
I do not know what’s going on there, but it’s not an issue. It’s obviously wrong but that’s okay. This is just trying to learn on a noisy cosine alone. Versus being trained on a noisy+smooth cosine.

It’s just an example of how to use pyESN

**Comment by robfairh** [comment]
Cool! Merging.

**Pull request merged**
