### PR TITLE
Lorenz examples and tests

### LINKED ISSUE #52: [Good First Issue] Add tests for lorenz96.py
This issue can be closed when tests have been added for ``lorenz96.py`` in a file called ``tests/test_lorenz96.py``

### LINKED ISSUE #58: Update function docstrings to be in line with Numpy style guide
It turns out, I've been wrong about a minor detail in the numpy style for a long time. 
```python
"""
this func... 
Parameters:
----------------
"""
```
There should be no colon next to "parameters" (or "returns" for that matter). 

This issue can be closed when the documentation in this repository has been updated.
You can read the numpy style guide [here](https://numpydoc.readthedocs.io/en/latest/format.html).

### LINKED ISSUE #59: Convert jupyter notebook Lorenz examples to rst examples
Currently, examples for using the ``lorenz.py`` module are in the ``lorenz96-example.ipynb``, Jupyter notebook. 

This issue can be closed when the file ``examples_lorenz.rst`` has examples of how to use the functions and how they should behave. see ``examples_sunrise.rst`` for inspiration.

**Note:** Any examples that use ``esn_prediction`` or similar function should remind readers that ``pyESN`` is a requirement for this package.

### PR DESCRIPTION
**Pull request by nsryan2**
This pr closes #52, closes #59,and closes #58. It has tests and examples for the four lorenz functions. All of the tests pass, and all of the documentation compiles correctly. I didn't make any plots for the lorenz functions, because I wasn't sure what to call the examples. But I can certainly add them if you'd like. 

edit: Oh, and the lorenz example jupyter notebook was importing the lorenz script wrong so I changed that.

### CODE REVIEW

**Review by samgdotson — CHANGES_REQUESTED** [review]
It all looks pretty good, definitely add plots for the 1963 model and the 1996 model. Similar to ``sunrise.py`` it's not a useful module unless we can visually verify what is being done. 

I noticed a couple of things that were *my* mistake again in writing docstrings, but would be good to change now. 
```python
"""
Required parameters are:
       "n_reservoir" : int, the reservoir size
       "sparsity" : float, the sparsity of the reservoir
      ....
"""
```
This should have a (*) character in front of the parameters like so:
```python
"""
Required parameters are:
       * "n_reservoir" : int, the reservoir size
       * "sparsity" : float, the sparsity of the reservoir
      ....
"""
```
Otherwise they won't show up as a list on the docs. This behavior is present in a few functions in ``tools.py`` and ``optimizer.py``.  Finally, in ``esn_prediction`` in ``tools.py``, this part
```python
"""
    E.g. Two datasets trained together

    >>> X_in = np.concatenate([[set1, set2]], axis=1)
    >>> pred = esn_prediction(X_in.T, params)
"""
```
Needs to be indented farther (so that it's inside the ``data : numpy array`` string... ) so that the example shows up in the docs.
```python
"""
    ---> E.g. Two datasets trained together

    --->  >>> X_in = np.concatenate([[set1, set2]], axis=1)
    --->  >>> pred = esn_prediction(X_in.T, params)
"""
```
Finally, notice how some examples can be done from WITHIN the function docstring? That might help condense some of your work.

**Review by samgdotson — COMMENTED** [review]
Everything looks good, thanks for making these changes. Before I merge, what is the ``.DS_Store`` file? If it's a built file (as with all built files) it should not be included in the PR. Maybe add it to the ``.gitignore``

**Comment by nsryan2** [comment]
I'm not sure how that got into the merge, thanks for the catch! I removed it and added .ds_store to the .gitignore just how .snakemake was above it.

**Review by samgdotson — APPROVED** [review]
Looks good! Merging

**Pull request merged**
